/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdminStats = IDL.Record({
  'totalPendingBooks' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalBooks' : IDL.Nat,
  'totalApprovedBooks' : IDL.Nat,
});
export const BookStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Time = IDL.Int;
export const BookView = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookStatus,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'viewCount' : IDL.Nat,
  'genre' : IDL.Text,
  'pdfUrl' : IDL.Text,
  'coverUrl' : IDL.Text,
  'editCount' : IDL.Nat,
  'uploadDate' : Time,
  'uploadedBy' : IDL.Principal,
});
export const Bookmark = IDL.Record({
  'user' : IDL.Principal,
  'bookId' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'joinDate' : Time,
});
export const ReadingProgress = IDL.Record({
  'user' : IDL.Principal,
  'bookId' : IDL.Nat,
  'lastPage' : IDL.Nat,
  'lastRead' : Time,
});
export const User = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'joinDate' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBookmark' : IDL.Func([IDL.Nat], [], []),
  'approveBook' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'editBook' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getApprovedBooks' : IDL.Func([], [IDL.Vec(BookView)], ['query']),
  'getBookById' : IDL.Func([IDL.Nat], [IDL.Opt(BookView)], ['query']),
  'getBookmarks' : IDL.Func([], [IDL.Vec(Bookmark)], ['query']),
  'getBooksByAuthor' : IDL.Func([IDL.Text], [IDL.Vec(BookView)], ['query']),
  'getBooksByGenre' : IDL.Func([IDL.Text], [IDL.Vec(BookView)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMostPopularBooks' : IDL.Func([], [IDL.Vec(BookView)], ['query']),
  'getMostViewedBooks' : IDL.Func([], [IDL.Vec(BookView)], ['query']),
  'getMyUploadedBooks' : IDL.Func([], [IDL.Vec(BookView)], ['query']),
  'getPendingBooks' : IDL.Func([], [IDL.Vec(BookView)], ['query']),
  'getReadingProgress' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ReadingProgress)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
  'incrementBookView' : IDL.Func([IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([IDL.Text], [], []),
  'rejectBook' : IDL.Func([IDL.Nat], [], []),
  'removeBookmark' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveReadingProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'uploadBook' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdminStats = IDL.Record({
    'totalPendingBooks' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalBooks' : IDL.Nat,
    'totalApprovedBooks' : IDL.Nat,
  });
  const BookStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Time = IDL.Int;
  const BookView = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookStatus,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'viewCount' : IDL.Nat,
    'genre' : IDL.Text,
    'pdfUrl' : IDL.Text,
    'coverUrl' : IDL.Text,
    'editCount' : IDL.Nat,
    'uploadDate' : Time,
    'uploadedBy' : IDL.Principal,
  });
  const Bookmark = IDL.Record({ 'user' : IDL.Principal, 'bookId' : IDL.Nat });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'joinDate' : Time,
  });
  const ReadingProgress = IDL.Record({
    'user' : IDL.Principal,
    'bookId' : IDL.Nat,
    'lastPage' : IDL.Nat,
    'lastRead' : Time,
  });
  const User = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'joinDate' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBookmark' : IDL.Func([IDL.Nat], [], []),
    'approveBook' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'editBook' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getApprovedBooks' : IDL.Func([], [IDL.Vec(BookView)], ['query']),
    'getBookById' : IDL.Func([IDL.Nat], [IDL.Opt(BookView)], ['query']),
    'getBookmarks' : IDL.Func([], [IDL.Vec(Bookmark)], ['query']),
    'getBooksByAuthor' : IDL.Func([IDL.Text], [IDL.Vec(BookView)], ['query']),
    'getBooksByGenre' : IDL.Func([IDL.Text], [IDL.Vec(BookView)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMostPopularBooks' : IDL.Func([], [IDL.Vec(BookView)], ['query']),
    'getMostViewedBooks' : IDL.Func([], [IDL.Vec(BookView)], ['query']),
    'getMyUploadedBooks' : IDL.Func([], [IDL.Vec(BookView)], ['query']),
    'getPendingBooks' : IDL.Func([], [IDL.Vec(BookView)], ['query']),
    'getReadingProgress' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ReadingProgress)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
    'incrementBookView' : IDL.Func([IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([IDL.Text], [], []),
    'rejectBook' : IDL.Func([IDL.Nat], [], []),
    'removeBookmark' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveReadingProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'uploadBook' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };