/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'totalPendingBooks' : bigint,
  'totalUsers' : bigint,
  'totalBooks' : bigint,
  'totalApprovedBooks' : bigint,
}
export type BookStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface BookView {
  'id' : bigint,
  'pdf' : [] | [ExternalBlob],
  'status' : BookStatus,
  'title' : string,
  'cover' : [] | [ExternalBlob],
  'description' : string,
  'author' : string,
  'viewCount' : bigint,
  'genres' : Array<string>,
  'editCount' : bigint,
  'uploadDate' : Time,
  'uploadedBy' : Principal,
}
export interface Bookmark { 'user' : Principal, 'bookId' : bigint }
export type ExternalBlob = Uint8Array;
export interface ReadingProgress {
  'user' : Principal,
  'bookId' : bigint,
  'lastPage' : bigint,
  'lastRead' : Time,
}
export type Time = bigint;
export interface User {
  'principal' : Principal,
  'displayName' : string,
  'joinDate' : Time,
}
export interface UserProfile { 'displayName' : string, 'joinDate' : Time }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBookmark' : ActorMethod<[bigint], undefined>,
  'approveBook' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'editBook' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      Array<string>,
      [] | [ExternalBlob],
      [] | [ExternalBlob],
    ],
    undefined
  >,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getApprovedBooks' : ActorMethod<[], Array<BookView>>,
  'getBookById' : ActorMethod<[bigint], [] | [BookView]>,
  'getBookmarks' : ActorMethod<[], Array<Bookmark>>,
  'getBooksByAuthor' : ActorMethod<[string], Array<BookView>>,
  'getBooksByGenre' : ActorMethod<[string], Array<BookView>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMostPopularBooks' : ActorMethod<[], Array<BookView>>,
  'getMostViewedBooks' : ActorMethod<[], Array<BookView>>,
  'getMyUploadedBooks' : ActorMethod<[], Array<BookView>>,
  'getPendingBooks' : ActorMethod<[], Array<BookView>>,
  'getReadingProgress' : ActorMethod<[bigint], [] | [ReadingProgress]>,
  'getTotalActiveReaders' : ActorMethod<[], bigint>,
  'getTotalAuthors' : ActorMethod<[], bigint>,
  'getTotalBooks' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [User]>,
  'incrementBookView' : ActorMethod<[bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[string], undefined>,
  'rejectBook' : ActorMethod<[bigint], undefined>,
  'removeBookmark' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveReadingProgress' : ActorMethod<[bigint, bigint], undefined>,
  'uploadBook' : ActorMethod<
    [
      string,
      string,
      string,
      Array<string>,
      [] | [ExternalBlob],
      [] | [ExternalBlob],
    ],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];